### ISSUE TITLE
Regiones de Chile duplicadas

### ISSUE THREAD

**Issue by ivanMSC** [DataScienceResearchPeru/covid-19_latinoamerica#1]
Las regiones de Los Rios y Los Lagos están duplicadas en los reportes diarios.

**Comment by pablodz** [comment]
Trabajando en repararlo, puedes indicarme tu correo porfavor para darte acceso al repositorio.

**Comment by ivanMSC** [comment]
Por favor, usa mi nombre de usuario para compartir acceso. Gracias.

**Comment by pablodz** [comment]
Genial, confirmame porfa si tienes acceso y si es el suficiente.
Acabo de solucionar las filas duplicadas, haré un commit.
Ojo, se está viendo agregar columnas importantes tales como "Fecha inicio de síntomas" ya que sirven para investigaciones epidemiológicas.

**Comment by ivanMSC** [comment]
Confirmo acceso! Gracias.
