### ISSUE TITLE
Algunas coordenadas de Perú están invertidas

### ISSUE THREAD

**Issue by ivanMSC** [DataScienceResearchPeru/covid-19_latinoamerica#10]
**Describe the bug**
Algunas coordenadas de Perú están invertidas

**Code and Logs and screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/35350256/77608358-bc1bb300-6efb-11ea-9f90-6bc5c6604f7e.png)

**Comment by pablodz** [comment]
Verificando a la brevedad las coordenadas https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/utils/iso3312_latinamerica.csv#L7

**Comment by pablodz** [comment]
@ivanMSC puedes verificar porfavor  hice el siguiente commit https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/3b055d875f185408f936100a32a7fe35c5111749

**Comment by ivanMSC** [comment]
PE-JUN esta mal. Creo que falta el signo negativo en su longitud
![image](https://user-images.githubusercontent.com/35350256/77609797-b627d100-6eff-11ea-8edf-342813dff919.png)

**Comment by pablodz** [comment]
@ivanMSC Sí, solo faltaba el signo negativo, ya lo actualicé en el commit https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/c3f637455e6a667b23d23b4880f9173342356822

**Comment by ZurMaD** [comment]
Se agregó data de Brazil, sería bueno probar para ver si las coordenadas son correctas.
