### ISSUE TITLE
Separar información no relacionada a casos COVID-19

### ISSUE THREAD

**Issue by carranco-sga** [DataScienceResearchPeru/covid-19_latinoamerica#11]
**Describe the bug**
Creo que en ánimos de mantener mejor la información del repositorio, conviene separar los datos que se plantean agregar (variables económicas e infraestructura hospitalaria) y moverlos a un repositorio adicional, dejando este exclusivamente para datos sobre los casos de COVID-19 y agregando un enlace para quienes deseen consultar la información adicional.

**Comment by pablodz** [comment]
Una decisión importante, creo que necesita la opinión de todos los colaboradores.

**Comment by scratchmex** [comment]
Estoy de acuerdo con @carranco-sga . La información de latam_extra_data/ creo que no tiene relación directa con el propósito de esta repo que es condensar todos los casos de latinoamérica.

**Comment by pablodz** [comment]
Enviado a https://github.com/DataScienceResearchPeru/covid-19_latinoamerica_extra
