### ISSUE TITLE
Formato de contribución y guías

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#12]
Actualmente no existen guías rápidas para los que contribuyen al proyecto y los que recién se van anexando.

Falta:

1.  Videos explicativos.
2.  Guías y plantillas para Github
3.  Actualización de archivos README's dentro de cada carpeta 
4.  Otras ideas que puedan surgir para simplificar la contribución.
5. Soporte para otros idiomas

**Comment by ZurMaD** [comment]
@all-contributors add @ZurMaD for design

**Comment by pablodz** [comment]
Softwares para las guías:
- `Visual Studio Code` (recomendado)
- `Microsoft Excel` (no recomendado)
- `En bloc de notas` (no recomendado)
- `Directo en Github` (indiferente)

**Comment by pablodz** [comment]
Se usará https://readthedocs.org/ para las guías. Si quieres aportar contesta a este comentario.

**Comment by pablodz** [comment]
No hubo requerimientos por documentación exacta, se asume que la data como está es entendible e intituitivo
