### ISSUE TITLE
Lista de centros de salud no encontrada

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#13]
En la búsqueda de la lista de centros de salud, que en [algunos países](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/tree/master/latam_extra_data/latam_health_infraestructure) es de acceso público, se han encontrado nula información en algunos países (detallado en el enlace anterior) y se optaría por encontrar dicha información mediante otros métodos.

**Comment by carranco-sga** [comment]
Respecto a México, la información se desglosa en diferentes volúmenes disponibles [aquí](http://www.dgis.salud.gob.mx/contenidos/publicaciones/p_bie_gobmx.html). La lista, por ejemplo, del número de camas, se encuentra en el volumen 1. Los datos más actuales que he encontrado son de 2017.

**Comment by pablora19** [comment]
Ecuador tiene data hasta 2018, de camas publicas y privadas, por especialidad

**Comment by pablodz** [comment]
Issue cerrado, se buscará apoyo de colaboradores para buscar data perteneciente a rubros distintos al covid-19
