### ISSUE TITLE
Argentina - Revisión 2020-03-29

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#15]
**Describe the bug**
Se encontró una incosistencia en el archivo `2020-03-29.csv`, porfavor @martingra podrías revisar este commit que se realizó para que Bolivia pueda subir su información https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/ce86552c2022ca0b3610018779276f88a3511021#diff-5760954246cbe4ad92bffaf88a4afd72 
Hay una fila sobrante que se subió

**Expected behavior**
Revisar y confirmar los números, finalmente cerrar este Issue.

**Comment by martingra** [comment]
perdón, al pegar los valores no me di cuenta que faltaba la provincia de Santiago del Estero en el archivo, y por eso invadí el primer registro de Bolivia.

**Comment by pablodz** [comment]
Cierto, acabo de verificar el archivo `example.csv` que duplico para crear los archivos para días siguientes no tiene Santiado del Estero incluído, haré un commit para arreglar el `example.csv` y para el día `2020-03-30.csv`, para el día `2020-03-29.csv` podrías arreglarlo?

**Comment by pablodz** [comment]
https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/e00263c62feeecd97e66aecf7cb94e071e154fd8 arreglado archivos `2020-03-28` y `2020-03-29` favor de revisar el archivo `2020-03-27` ya que no tenía la fila correspondiente a `Santiago del Estero`.

**Comment by martingra** [comment]
subido

**Comment by pablodz** [comment]
Approved
