### ISSUE TITLE
Completar utils/iso3312_latinamerica.csv

### ISSUE THREAD

**Issue by ivanMSC** [DataScienceResearchPeru/covid-19_latinoamerica#16]
Por favor, a los encargados de cada país, no olvidar este archivo.

Gracias.

**Comment by pablodz** [comment]
Faltan (Confirmar con el comentario líneas abajo):
- Argentina @martingra 
- Bolivia @mamanipatricia 
- Brazil @ZurMaD 
- Colombia [Sin responsable]
- Costa Rica [Sin responsable]
- Dominican Republic [Sin responsable]
- Ecuador @pablora19 
- El Salvador [Sin responsable]
- Honduras [Sin responsable]
- Nicaragua [Sin responsable]
- Panama [Sin responsable]
- Paraguay [Sin responsable]
- Uruguay [Sin responsable]

Agregar `Latitud`, `Longitud` para cada subdivisión de cada país en [este archivo](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/utils/iso3166-2.csv) (Se cambió de nombre), confirmar una vez realizado los cambios, muchas gracias por su aporte.

**Comment by pablodz** [comment]
Se han actualizado las coordenadas para los siguientes países: (Actualizaré conforme van agregando):
- Ecuador https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/7e8d5720930752cd6b4e7ba8298f52bad984b6a5
- Argentina https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/1fbc5b78f0f7ed80a55935cdf2dc06ca0de6f6e9
- Bolivia https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/1fbc5b78f0f7ed80a55935cdf2dc06ca0de6f6e9
- Colombia https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/5103ad0540ed49de230468c1e5522826973608b2 (Coordenadas de Vaupé no encontradas)
- Costa Rica https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/2ce4fa594cd1816221fc99cce84d5cd8d785387f
- Dominican Republic https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/5a504dabfcc5e4c2aa4d39185b874b3fb4c9e38a
- El Salvador https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/9f90397c412b63a3162c91696e9ea81c1446e87d
- Nicaragua https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/62b0df45d9f482431c52c254c20fcfcf91e8ee39
- Panama https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/9e1a51e83e0f37ecd9b2a4061bd922a08aaef2a9
- Venezuela (Falta coordenadas de Distrito Capital VE-A)
- Paraguay https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/a6eef7b1ab5e350fbf8e7bf3bf765f65648ab6f4
- Uruguay https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/e1377f61dbc374532d11ef5974180fe3722e85c1

This data is necesarry for #17

**Comment by pablodz** [comment]
Porfavor, los que ya están empleando mapas validar la data para poder cerrar el Issue.

**Comment by ivanMSC** [comment]
Problemas en Honduras

![image](https://user-images.githubusercontent.com/35350256/78075076-39bb4500-737a-11ea-9282-4fdaa813d52d.png)

**Comment by pablodz** [comment]
- Honduras arreglado, favor de revisar @ivanMSC (https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/4dd9b443b972ce23075fce99d40fc0f34dbcbd0b)

**Comment by ivanMSC** [comment]
Agregué unas que aún faltaban (4368486). Estaría completo

**Comment by pablodz** [comment]
Perfecto, podemos cerrar el Issue entonces.

**Comment by ivanMSC** [comment]
Encontré algunos errores en Brasil. Hice un repaso por todas las coordenadas con un geocoder de google que al parecer dio buen resultado. (5efb3fe)
