### ISSUE TITLE
Maps Covid-19 Latin America

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#17]
**Is your feature request related to a problem? Please describe.**
We need a map.

**Comment by ivanMSC** [comment]
Yo manejo Google Data Studio. Construiré un dashboard. Veremos como queda.

**Comment by pablodz** [comment]
Excelente, compartes el enlace para ponerlo en el `README.md` del repo, se sumaran todos los demás dashboards si es que hubiesen también.

**Comment by ivanMSC** [comment]
Versión mobile: https://datastudio.google.com/reporting/c817609e-3351-4614-acb7-3e72fdbc6d6a/page/QkcKB

Versión desktoop: https://datastudio.google.com/u/2/reporting/9b824956-4055-46da-8c40-0d46ded5ffba/page/QkcKB

![image](https://user-images.githubusercontent.com/35350256/78097438-abaf8080-73b2-11ea-9bbc-b3f946b18718.png)

**Comment by pablodz** [comment]
Excelente, se agregará al `README.md` del principal

**Comment by pablodz** [comment]
@ivanMSC Se han agregado 3 países y 7 dependencias pertenecientes a Latinoamérica (#40) Faltaría agregar sus coordenadas y ya estoy buscando `Maintainers` para esos lugares.

**Comment by ivanMSC** [comment]
@ZurMaD Me encargo de las coordenadas!

**Comment by pablodz** [comment]
Encontré una [página web ](https://covid19.health/) que cruza la data que subimos con otros repositorios. Gracias a todos los colaboradores!
