### ISSUE TITLE
Coordinación entre colaboradores del repositorio

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#18]
**Is your feature request related to a problem? Please describe.**
Falta un canal en el que podamos comunicarnos de forma directa y comunicar los cambios que se realizan de forma centralizada.

**Describe the solution you'd like**
Un servidor en:
- Discord
- Slack
- Whatsapp
- Otro: (Propuestas)

**Describe alternatives you've considered**
Uso cualquier medio, en mi caso no tendría inconvenientes.

**Comment by leytzher** [comment]
Mi preferencia es Slack

**Comment by pablodz** [comment]
@ariasbordahugo @carranco-sga @Chilangdon20 @dfuribez @diegocl02 @ivanMSC @josetup123 @leytzher @mamanipatricia @martingra @pablora19 @pablorea @rafnixg @RcrdPhysics @rendergraf @ZurMaD

**Comment by ivanMSC** [comment]
Voto por slack

**Comment by pablorea** [comment]
Propongo usar telegram, me parece una opción bastante completa

**Comment by Chilangdon20** [comment]
WhatsApp  o slack

**Comment by rafnixg** [comment]
Voto por Slack tambien.

**Comment by diegocl02** [comment]
Voto por Slack

**Comment by dfuribez** [comment]
Slack o Telegram

**Comment by RcrdPhysics** [comment]
Hello there! Slack!

**Comment by martingra** [comment]
Slack (Y)

**Comment by mamanipatricia** [comment]
Slack o Telegram!

**Comment by pablora19** [comment]
Voto en blanco, me sumo a la mayoria

**Comment by pablodz** [comment]
Respondan en Issue #47
