### ISSUE TITLE
Adding new columns: quantity of test realized?

### ISSUE THREAD

**Issue by jtupayachi** [DataScienceResearchPeru/covid-19_latinoamerica#19]
Modificacion estructura DB:
deberia agregarse pruebas realizadas como columma?

La finalidad:
saber cuantas personas fueron a realizarse la prueba sin embargo no dieron positivos

**Comment by ivanMSC** [comment]
En Chile tenemos esos datos, pero no actualizados día a día. Creo que cada dos días.

**Comment by pablodz** [comment]
Para el caso de Perú, se cuenta con la data.

@mamanipatricia El caso de Bolivia?

**Comment by martingra** [comment]
Estuve buscando si se publica este dato en algún lado para Argentina pero no lo pude encontrar todavía.

**Comment by pablodz** [comment]
En el caso de `Costa Rica` sí cuentan con la data y nos la proporcionan mediante un API.

**Comment by carranco-sga** [comment]
Para México sí se cuentan con los datos.

**Comment by mamanipatricia** [comment]
En Bolivia tenemos los siguientes casos: Casos Confirmados, Casos Recuperados, Decesos, Casos Sospechosos, Casos Descartados.

**Comment by pablodz** [comment]
Se empezará a recopilar test realizados por día por país, porfavor empezar a buscar la información
