### ISSUE TITLE
Crear archivo de georreferencia

### ISSUE THREAD

**Issue by ivanMSC** [DataScienceResearchPeru/covid-19_latinoamerica#2]
Sugiero eliminar las columnas `Latitude` y `Longitude`. En su lugar, crear un archivo nuevo, por ejemplo `Georeferencing.csv` con los campos: `Province/State`, `Country/Region`, `Latitude`, `Longitude`, etc con información relativa a cada subdivisión administrativa.
De esta forma evitamos repetir información innecesariamente, resultando en una base de datos más robusta.

**Comment by pablodz** [comment]
Creo que la necesitan para los mapas automatizados, confirmaré si es necesaria las columnas  `Latitude`, `Longitude` .

**Comment by ivanMSC** [comment]
Imagino que sí son necesarias. Pero yo opino que sería mejor formar una base de datos relacional. Si se necesita hacer un mapa se llama a la tabla de georreferecia y se hace la relación.

**Comment by ivanMSC** [comment]
O tal vez, no borrar las columnas de lat y long, pero de todas formas crear una tabla de georreferencia, incluyendo más datos como por ejemplo población, densidad, población rural, población urbana, etc

**Comment by pablodz** [comment]
> O tal vez, no borrar las columnas de lat y long, pero de todas formas crear una tabla de georreferencia, incluyendo más datos como por ejemplo población, densidad, población rural, población urbana, etc

Sí, creo que lo segundo podemos hacerlo

**Comment by pablodz** [comment]
¿Podríamos agregar alguna [norma ISO](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) para referenciar la data? ¿Conoces de algo sobre eso, tengo conocimiento nulo? Ya consulté y no es necesaria para los mapas tener `Latitud` y `Longitud` en cada fila

Update 17:55 GTM-5
Encontré que existe una norma mundial con código asignado para ciudad del mundo. 
http://www.unece.org/cefact/codesfortrade/codes_index.html

**Comment by ivanMSC** [comment]
La norma ISO 3166-2 es la que tendríamos que usar. 
> http://www.unece.org/cefact/codesfortrade/codes_index.html

eso esta muy bueno podríamos usarlo. Supongo que con con el primer nivel de subdivisión administrativa debería ser suficiente.

**Comment by rendergraf** [comment]
En mi caso las estoy usando para referenciar ciudades en las coordenadas correspondientes, creo que deberían estar allí, para alguien sería más lógico y simple extraer esos datos.

Mi mapa: https://github.com/covidvenezuela/covid19-venezuela/blob/master/static/geojson/venezuela.json

Aquí las coordenadas de cada ciudad para crear el punto geográfico: https://github.com/covidvenezuela/covid19-venezuela/blob/master/static/map/estados.json

En cuanto a la norma ISO 3166-2 en mi caso sería https://es.wikipedia.org/wiki/ISO_3166-2:VE
¿Esto remplazaría a las dos primeras columnas (Province/State y Country/Region) ?

**Comment by pablodz** [comment]
No, es un agregado, luego quizás puede removerse, por ahora no.

> ¿Esto remplazaría a las dos primeras columnas (Province/State y Country/Region) ?

¿Entonces, ideas de cómo y dónde poner esa tabla de referencias?
Encontré estos [repositorios](https://github.com/search?q=+iso+3166&type=)

**Comment by pablodz** [comment]
Se creó un archivo que rige bajo ISO 3166-2 para países de latinoamérica. Commit https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/83521e8dc436db2827815104e19caf3395ceec09 

Falta:

- Agregar datos de `Longitud`
- Agregar datos de `Latitud`

**Comment by rendergraf** [comment]
Agregue los de Ecuador y Perú

**Comment by rendergraf** [comment]
Estoy probando las coordenadas co un mapa

![image](https://user-images.githubusercontent.com/5533099/77381634-cfd8e500-6d54-11ea-964b-2222a603b5d7.png)

![image](https://user-images.githubusercontent.com/5533099/77381728-031b7400-6d55-11ea-8b53-cc1f24899083.png)

![image](https://user-images.githubusercontent.com/5533099/77381803-26deba00-6d55-11ea-9a15-8b4117268410.png)

![image](https://user-images.githubusercontent.com/5533099/77381840-40800180-6d55-11ea-8f1c-4f7eb32aa439.png)

**Comment by pablodz** [comment]
Se ve buenísimo. Aún falta completar el normado ISO 3166-2

**Comment by pablodz** [comment]
Se completó el normado ISO porfavor revisar los cambios efectuados.
