### ISSUE TITLE
Absence of data

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#22]
**[Last Update: 2020-03-04T16:29:02]**
**Describe the data error**
First of all, thanks of all contributors.
After @ivanMSC helped us with the [elaboration of the map](https://datastudio.google.com/u/2/reporting/9b824956-4055-46da-8c40-0d46ded5ffba/page/QkcKB) we can easily see the absence of data. I will label the maintainers corresponding to each country so that they can review and in case of errors correct the information.

**Where's the error?**
Error founded per country (For confirmed cases only)
- Argentinta (ALL OK):
- Bolivia (@mamanipatricia):  ALL FIXED (2020-03-04), commits below
- Brazil (All OK):
- Chile (All OK)
- Honduras (Automated  ALL OK)
- Mexico (@carranco-sga ALL OK)
- Costa Rica (Automated, external API provided in progress to validate information, waiting)
- Dominican Republic (Automatic @ZurMaD ):
![image](https://user-images.githubusercontent.com/28235457/78738558-c4bab300-7917-11ea-808d-f5bafcd812b0.png)

- El Salvador (unmaintained)
- Nicaragua (unmaintained)
- Panama (unmaintained)
- Paraguay (unmaintained)
- Uruguay (unmaintained)

- Colombia (Automated @dfuribez ):
![image](https://user-images.githubusercontent.com/28235457/78738731-372b9300-7918-11ea-82b7-24a71361f6c0.png)

    - [`2020-03-23.csv`](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/latam_covid_19_data/latam_covid_19_daily_reports/2020-03-23.csv) 
    - [`2020-03-22.csv`](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/latam_covid_19_data/latam_covid_19_daily_reports/2020-03-22.csv) 

(All CO-X codes, looks like general error this day)

- Ecuador (@pablora19 ):
![image](https://user-images.githubusercontent.com/28235457/78339804-b0af3400-755a-11ea-8440-14b2880ee9fd.png)
    - No data for `2020-03-03` to `2020-03-12.csv`. [Daily report directory](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/tree/master/latam_covid_19_data/latam_covid_19_daily_reports)

- Peru (@ZurMaD @diegocl02 ):
![image](https://user-images.githubusercontent.com/28235457/78740459-6f34d500-791c-11ea-8531-c94133125db3.png)

    - [`2020-03-16.csv`](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/latam_covid_19_data/latam_covid_19_daily_reports/2020-03-16.csv) Temporaly duplicated day 29
    - [`2020-03-17.csv`](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/latam_covid_19_data/latam_covid_19_daily_reports/2020-03-17.csv)
    - [`2020-03-18.csv`](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/latam_covid_19_data/latam_covid_19_daily_reports/2020-03-18.csv)
    - [`2020-03-10.csv`](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/latam_covid_19_data/latam_covid_19_daily_reports/2020-03-19.csv)
 

- Venezuela (@rendergraf ):
![image](https://user-images.githubusercontent.com/28235457/78383758-8c754680-759e-11ea-9fa3-d99c47d19a3c.png)

 - Multiple data not founded, we're going to call help to support Venezuela's report.

**Additional information**
Don't forget to update the date the data is updated in [this file](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/README.md).

**Comment by carranco-sga** [comment]
@ZurMaD  Thanks for noting the errors in my data. I'll fix them ASAP.

**Comment by carranco-sga** [comment]
Mexico's data should be fixed by f300374741d7df2f2659688f4ec045dd2d38625b.

**Comment by mamanipatricia** [comment]
I fixed the error (2020-03-28.csv (El Beni no data for 29,30,31 of March)) , but for this  one (2020-03-21.csv (Inconsistency)) I don't have the data to fix and fill in.

**Comment by pablora19** [comment]
Ecuador data completed.

**Comment by pablodz** [comment]
> Ecuador data completed.

Thanks for all, please review of 2 to 13 of March, tell us if you need help with that to convocate volunteers.

**Comment by pablodz** [comment]
Absence of data will show in different Issues one per country.
