### ISSUE TITLE
[Don't answer] For contributor's table on README

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#24]
[Don't answer this thread]

**Comment by pablodz** [comment]
@all-contributors please add @ZurMaD for projectManagement

**Comment by ZurMaD** [comment]
@all-contributors please add @rendergraf for data
@all-contributors please add @RcrdPhysics 
@all-contributors please add @rafnixg 
@all-contributors please add @pablorea 
@all-contributors please add @pablora19 
@all-contributors please add @martingra 
@all-contributors please add @mamanipatricia 
@all-contributors please add @leytzher 
@all-contributors please add @josetup123 
@all-contributors please add @ivanMSC 
@all-contributors please add @diegocl02 
@all-contributors please add 
@all-contributors please add 
@all-contributors please add

**Comment by ZurMaD** [comment]
@all-contributors please add @rendergraf for data
@all-contributors please add @RcrdPhysics for data
@all-contributors please add @rafnixg for data
@all-contributors please add @pablorea for data
@all-contributors please add @pablora19 for data
@all-contributors please add @martingra for data
@all-contributors please add @mamanipatricia for data
@all-contributors please add @leytzher for data
@all-contributors please add @josetup123 for data
@all-contributors please add @ivanMSC for data
@all-contributors please add @diegocl02 for data
@all-contributors please add @dfuribez for data 
@all-contributors please add @hilangdon20 for data 
@all-contributors please add @carranco-sga for data
@all-contributors please add @ariasbordahugo for data
@all-contributors please add @adtor97 for for data for data

**Comment by ZurMaD** [comment]
@all-contributors please add @RcrdPhysics for data

**Comment by ZurMaD** [comment]
@all-contributors please add @RcrdPhysics for 🔣

**Comment by ZurMaD** [comment]
@all-contributors please add @rendergraf for doc
@all-contributors please add @RcrdPhysics for doc
@all-contributors please add @rafnixg for doc
@all-contributors please add @pablorea for doc
@all-contributors please add @pablora19 for doc
@all-contributors please add @martingra for doc
@all-contributors please add @mamanipatricia for doc
@all-contributors please add @leytzher for doc
@all-contributors please add @josetup123 for doc
@all-contributors please add @ivanMSC for doc
@all-contributors please add @diegocl02 for doc
@all-contributors please add @dfuribez for doc 
@all-contributors please add @hilangdon20 for doc 
@all-contributors please add @carranco-sga for doc
@all-contributors please add @ariasbordahugo for doc
@all-contributors please add @adtor97 for for doc for doc

**Comment by ZurMaD** [comment]
@all-contributors please add @rendergraf for doc
@all-contributors please add @RcrdPhysics for doc
@all-contributors please add @rafnixg for doc
@all-contributors please add @pablorea for doc
@all-contributors please add @pablora19 for doc
@all-contributors please add @martingra for doc
@all-contributors please add @mamanipatricia for doc
@all-contributors please add @leytzher for doc
@all-contributors please add @josetup123 for doc
@all-contributors please add @ivanMSC for doc
@all-contributors please add @diegocl02 for doc
@all-contributors please add @dfuribez for doc
@all-contributors please add @hilangdon20 for doc
@all-contributors please add @carranco-sga for doc
@all-contributors please add @ariasbordahugo for doc
@all-contributors please add @adtor97 for for doc for doc

**Comment by pablodz** [comment]
@all-contributors please add @RcrdPhysics for doc

**Comment by ZurMaD** [comment]
@all-contributors please add @rendergraf for doc,
@all-contributors please add @RcrdPhysics for doc,
@all-contributors please add @rafnixg for doc,
@all-contributors please add @pablorea for doc,
@all-contributors please add @pablora19 for doc,
@all-contributors please add @martingra for doc,
@all-contributors please add @mamanipatricia for doc,
@all-contributors please add @leytzher for doc,
@all-contributors please add @josetup123 for doc,
@all-contributors please add @ivanMSC for doc,
@all-contributors please add @diegocl02 for doc,
@all-contributors please add @dfuribez for doc,
@all-contributors please add @hilangdon20 for doc,
@all-contributors please add @carranco-sga for doc,
@all-contributors please add @ariasbordahugo for doc,
@all-contributors please add @adtor97 for for doc for doc,

**Comment by pablodz** [comment]
@all-contributors please add @rendergraf for doc

**Comment by pablodz** [comment]
@all-contributors please add @rafnixg for doc

**Comment by pablodz** [comment]
@all-contributors please add @pablorea for doc

**Comment by pablodz** [comment]
@all-contributors please add @pablora19 for doc

**Comment by pablodz** [comment]
@all-contributors please add @martingra for doc

**Comment by pablodz** [comment]
@all-contributors please add @mamanipatricia for doc

**Comment by pablodz** [comment]
@all-contributors please add @leytzher for doc

**Comment by pablodz** [comment]
@all-contributors please add @josetup123 for doc

**Comment by pablodz** [comment]
@all-contributors please add @ivanMSC for doc

**Comment by pablodz** [comment]
@all-contributors please add @diegocl02 for doc

**Comment by pablodz** [comment]
@all-contributors please add @dfuribez for doc

**Comment by pablodz** [comment]
@all-contributors please add @hilangdon20 for doc

**Comment by pablodz** [comment]
@all-contributors please add @carranco-sga for doc

**Comment by pablodz** [comment]
@all-contributors please add @ariasbordahugo for doc

**Comment by pablodz** [comment]
@all-contributors please add @adtor97 for for doc for doc

**Comment by pablodz** [comment]
@all-contributors please add @josetup123 for doc Panamá
