### ISSUE TITLE
Cambiar nombre de repositorio

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#3]
Al principio fue `covid-19_pe` debido a que se pensaba a hacer solo para Perú pero ahora que abarca a toda latinoamérica, ¿qué nombre debería tener? @ivanMSC  @rendergraf

**Comment by ivanMSC** [comment]
covid-19_latinoamerica

**Comment by pablodz** [comment]
Se cambiará el nombre a `covid-19_latinoamerica`
