### ISSUE TITLE
Edición de CSV

### ISSUE THREAD

**Issue by ivanMSC** [DataScienceResearchPeru/covid-19_latinoamerica#4]
Estaba usando Excel para editar el csv. Cuando hago un cambio en una línea del archivo y guardo, el diff me arroja cambios en **todas** las lineas del archivo. A qué se debe?

![image](https://user-images.githubusercontent.com/35350256/77241624-8ad97500-6bd3-11ea-86aa-5032ffa70e32.png)

**Comment by pablodz** [comment]
Creo que es algo del excel, aunque me parece raro porque en la imagen se ve que no ha cambiado nada. ¿Usas VScode?, hay un plugin para abrir archivos csv llamado `Edit csv` de `janisdd` una prueba cambiando una línea: 
![image](https://user-images.githubusercontent.com/28235457/77243764-b7918a80-6bdb-11ea-8133-9aac7f28f22d.png)

**Comment by ivanMSC** [comment]
Era excel.
