### ISSUE TITLE
Not all countries of Latin America considered in our repository

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#40]
We need to add 3 countries and 7 dependencies. 

Countries:

- Guatemala (GT)
- Haiti (HT)
- Cuba (CU)

Dependencies:

- French Guiana (GF)
- Guadeloupe (GP)
- Martinique (MQ)
- Puerto Rico (PR)
- Saint Martin (MF)
- Saint Barthélemy (BL)
- Saint Pierre and Miquelon (PM)

También podemos agregar (resto de países de América):

- Antigua y Barbuda
- Bahamas
- Barbados
- Belice
- Canadá
- Dominica
- Estados Unidos
- Granada
- Guyana
- Jamaica
- San Cristóbal y Nieves
- San Vicente y las Granadinas
- Santa Lucía
- Surinam
- Trinidad y Tobago

**Comment by pablodz** [comment]
@all-contributors please add @ncovgt2020 for doc Guatemala

**Comment by pablodz** [comment]
@all-contributors please add @Caospierre for doc

**Comment by ZurMaD** [comment]
Agregando departamentos de Haití, no fueron agredaos anteriormente. https://es.wikipedia.org/wiki/Hait%C3%AD

**Comment by pablodz** [comment]
@all-contributors please add @annaabsi  for doc and design
