### ISSUE TITLE
Panama data not according to top level division.

### ISSUE THREAD

**Issue by ivanMSC** [DataScienceResearchPeru/covid-19_latinoamerica#43]
**Describe the bug**
@josetup123 9474437 and a04547c 
Please, fix Panama data. It must be consistent with top level administrative divisions. Follow the template. Do NOT touch, modify, add or delete ISO codes or names.

**Expected behavior**
Panama has the following divisions:
```
PA-1,Bocas del Toro,Panama,,,,
PA-4,Chiriqui,Panama,,,,
PA-2,Cocle,Panama,,,,
PA-3,Colon,Panama,,,,
PA-5,Darien,Panama,,,,
PA-6,Herrera,Panama,,,,
PA-7,Los Santos,Panama,,,,
PA-8,Panama,Panama,,,,
PA-10,Panama Oeste,Panama,,,,
PA-9,Veraguas,Panama,,,,
PA-EM,Embera,Panama,,,,
PA-KY,Guna Yala,Panama,,,,
PA-NB,Ngabe-Bugle,Panama,,,,
```

**Files with the bug**

**Additional context**
It is important to be consistent. Please only modify data and not names, ISO codes or any other columns of the template.

**Comment by ivanMSC** [comment]
Also,@josetup123, the number of cases is supposed to be data of type int. So instead of `0.0`, the csv should read `0`. You made changes that affected other countries data (`CL`). Please double check the `diff` before commiting to make sure you're not affecting someone else's contribution.

**Comment by pablodz** [comment]
Resolveré el Issue #12 para evitar este tipo de inconvenientes

**Comment by pablodz** [comment]
@josetup123 tenemos un formato ya establecido porfa, para el caso de panamá los casos tiene que agruparse acorde a dicho formato. El cuál es de agrupar los casos para estas provincias:
![image](https://user-images.githubusercontent.com/28235457/78317626-6c0aa500-7528-11ea-84ec-663a699e6513.png)

El formato que subiste no será aceptado
![image](https://user-images.githubusercontent.com/28235457/78317646-7dec4800-7528-11ea-8e0f-76ae5e8a9c09.png)
Como menciona ivanMSC usemos enteros en lugar de `0.0` decimales. 

Por ahora voy a sacar tus commits porque he visto que también estás sobreescribiendo información sin verificar si hay cruce. Para solucionar esto te podría recomendar usar [GitKraken](https://www.gitkraken.com/)

**Comment by jtupayachi** [comment]
esta bien lo corregiré en estos dias
