### ISSUE TITLE
Slack Channel

### ISSUE THREAD

**Issue by leytzher** [DataScienceResearchPeru/covid-19_latinoamerica#47]
Hola, he creado el canal de Slack [covid19latinoamerica.slack.com](covid19latinoamerica.slack.com) para los colaboradores del grupo.
Aqui les dejo el link para que puedan subscribirse.
[https://join.slack.com/t/covid19latinoamerica/shared_invite/zt-d99sp09d-mcwZ3AmFI_kmj~kYryg74w](https://join.slack.com/t/covid19latinoamerica/shared_invite/zt-d99sp09d-mcwZ3AmFI_kmj~kYryg74w)

**Comment by pablodz** [comment]
@Cuica20 @ariasbordahugo @Caospierre @carranco-sga @Chilangdon20 @dfuribez @diegocl02 @ivanMSC @josetup123 @leytzher @mamanipatricia @martingra @pablora19 @pablorea @rafnixg @RcrdPhysics @rendergraf @ZurMaD 
Estaremos agradecidos de poder coordinar de una mejor manera por Slack
