### ISSUE TITLE
[Automation] Brazil & Costa Rica

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#50]
Parte de #52 
Encontré este [repositorio](https://github.com/elhenrico/covid19-Brazil-timeseries) de Brazil que lo actualizan diario.

¿Hay alguna forma de automatizar esto?

**Comment by pablodz** [comment]
Enlace a [API de costa rica](https://coronaviruscr.com/api/reports)

**Comment by dfuribez** [comment]
@ZurMaD Yo estoy actualizando los datos desde mi [repo](https://github.com/dfuribez/COVID-19-Colombia) con un script que estoy terminando de automatizar. Podría encargarme de escribir el script para automatizar la toma de los datos de brazil, pero sólo tengo tiempo desde el lunes. Si no hay problema con la fecha, yo me puedo encargar.

**Comment by pablodz** [comment]
> @ZurMaD Yo estoy actualizando los datos desde mi [repo](https://github.com/dfuribez/COVID-19-Colombia) con un script que estoy terminando de automatizar. Podría encargarme de escribir el script para automatizar la toma de los datos de brazil, pero sólo tengo tiempo desde el lunes. Si no hay problema con la fecha, yo me puedo encargar.

Excelente, no hay problema con la fecha. Te espero! @dfuribez

**Comment by dfuribez** [comment]
@ZurMaD al fin logré sacar algo de tiempo y el script está en 5cd21efa39acac9914ea2d0763dc3b1097109687 tengo que retocar un par de cosas, pero ya está listo para ser usado.

**Comment by pablodz** [comment]
¿Alguien logró avanzar con el de Costa Rica? Para no duplicar esfuerzos

**Comment by pablodz** [comment]
@dfuribez vi que ya automatizaste todo, podrías porfa sobreescribir los archivos de brazil desde el 26 de febrero con el script ya que hay errores menores en los que subí en su momento.

**Comment by dfuribez** [comment]
@ZurMaD el script para la automatización de los datos de Costa Rica está acá e202802e5a804d50d262eba61dd6069e28cd9995 sólo actualiza los casos confirmados ya que son los únicos que están reportando por región. Toca buscar las muertes y recuperodos.

Con respecto a Brazil, ya genero esos datos.

**Comment by pablodz** [comment]
Gracias @dfuribez !! No olvides subir también el script de Colombia. Excelente trabajo.
