### ISSUE TITLE
Scripts to automate 

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#52]
We need scripts to automate (Scripts go to [this folder](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/tree/master/utils/scripts)):
- Reports of absense of data (blank spaces in `2020-0X-XX.csv` - [Daily report folder](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/tree/master/latam_covid_19_data/latam_covid_19_daily_reports)). 
- API information obtain and update to our repository (Reply to #50 )
- Automation ( #53 #55 #56 #57 )
- Dashboards (ivanMSC is actually doing a good work here)
- Confirm our numbers with other repositories that has the numbers grouped per country.
- Others (Feel free to propose)

Please create new Issue of each script to automate to be well documented.
Thanks all contributors! Please call more volunteers :)

**Comment by ivanMSC** [comment]
Dashboard is already automated. Reloading data every one hour.

**Comment by pablodz** [comment]
> Dashboard is already automated. Reloading data every one hour.

Perfect.

**Comment by pablodz** [comment]
@ivanMSC Brazil y Costa Rica tienen scripts pero que actualizan los datos hasta un csv. No fue automatizado completamente porque no consigo manejar valores como blank_space, no entiendo porque python lo convierte a cero al guardarlo como archivo csv. Entonces, tenía pensado usar la [carpetas temporales](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/tree/master/utils/scripts/data_collection), es decir yo corro el código este me genera para tales días archivos csv mismo formato al de la data recolectada pero solo quiero extraer lo correspondiente de brazil y costa rica y pegarlo en las del `daily_report`. Es eso posible con el bot de App Google?

**Comment by ivanMSC** [comment]
Sí, con el bot de google apps se puede. Pero me queda la duda: de los csv en las carpetas temporales, cómo se sabe qué ceros deben ser espacios en blanco?

**Comment by pablodz** [comment]
Sería específico para cada país: `Brazil` y `Costa Rica` solo estan reportando `Confirmados` y `Muertos` por subdivisión de país. En el caso de `Recuperados` no hay data pública

**Comment by scratchmex** [comment]
Propongo usar [Github actions](https://github.com/features/actions) (en especial el [schedule](https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)) para automatizar el workflow de actualizar los csv's con Docker y hacer un amend automático al commit con [esta](https://github.com/stefanzweifel/git-auto-commit-action) acción cada vez que se modifiquen archivos de cada pais en cada repo. Esto contribuye a #87

**Comment by scratchmex** [comment]
Propongo usar [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) para tener un tracking de todas las repos sin repetir datos y así agregar toda la info en esta repo como referencia a la repo original. A discusión
