### ISSUE TITLE
[Automation] Cuba

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#53]
#52 dejo el enlace al repositorio que tiene enlace API para poder actualizar la data diaria de forma automática

https://github.com/correaleyval/covid19cuba_api

**Comment by dfuribez** [comment]
Con respecto a cuba, acá está el script 12dca6fa4a544ce48a6f26802d66494f8dd5362f sólo se reportan los casos confirmados.

**Comment by pablodz** [comment]
Endpoints
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/affected_municipalities.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/affected_provinces.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/cases_by_mode_of_contagion.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/cases_by_nationality.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/cases_by_sex.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/comparison_of_accumulated_cases.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/distribution_by_age_ranges.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/distribution_by_nationality_of_foreign_cases.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/evolution_of_cases_by_days.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/evolution_of_deaths_by_days.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/evolution_of_recovered_by_days.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/list_of_tests_performed.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/map_data.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/note.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/resume.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/tests_by_days.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/updated.json

https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/all.json

**Comment by dfuribez** [comment]
Esa API parece más completa, pero al igual que la otra, sólo reporta por región los casos confimados mas no las muertes ni recuperados, así que la información es la misma.

**Comment by pablodz** [comment]
Sí, creo que salen del mismo repositorio. Voy a mapear que data estamos actualizando, pondré un warning para  decir que la data confiable solo es confirmados y haré un listado por país. Gracias.

**Comment by ivanMSC** [comment]
@dfuribez @ZurMaD Hay un bug en Colombia:
![image](https://user-images.githubusercontent.com/35350256/78973836-b36fd300-7ade-11ea-9299-7b306632964f.png)

Los códigos ISO están confundidos. Me di cuenta porque en el mapa muestra cero donde no debe.

**Comment by pablodz** [comment]
Uhmmm Hay que usar el código ISO para identificar filas en lugar de los nombres.
¿Cómo arreglaríamos esto? Reemplazar el nombre nada más o qué errores más hay?

**Comment by ivanMSC** [comment]
Solo están cambiados los códigos. Ahí en la línea 90 debe ser CO-CHO, 91 CO-COR y 92 CO-CUN.
Opino que las columnas de pais y nombre de subdivisión son redundantes, pero que de todas formas son importantes para quien lee el archivo. En el caso de los sistemas de automatización, claro... sería más consistente referirse a los códigos ISO en lugar de a los nombres.
