### ISSUE TITLE
Data de Brasil parece estar equivocada

### ISSUE THREAD

**Issue by ivanMSC** [DataScienceResearchPeru/covid-19_latinoamerica#54]
**Describe the data error**
Por ejemplo, BR-ES esta en cero. No debería ser así.

**Where's the error?**

**Describe the solution you'd like**
Revisar los datos de Brasil, porque hubo varios commits que arrasaron con todo.

**Additional context**

**Comment by dfuribez** [comment]
¿Sólo faltan los datos para esa región?
Voy a revisar el script a ver qué está sucediendo.

**Comment by ivanMSC** [comment]
Faltan los de ese estado. Pero sugeriría revisar todo porque los ultimo commits cambiaron todo lo que había.

**Comment by dfuribez** [comment]
@ivanMSC Ya encontré el error, en nuestro dataset ese estado se llama "Espirit**u** Santo" y en el repo desde el que se están obteniendo los datos ese estado aparece como "Espirit**o** Santo" esa diferencia hace que pandas no me tomara los datos. Gracias por notarlo, en unos minutos debe quedar solucionado.

**Comment by dfuribez** [comment]
@ivanMSC Solucionado y de paso cambié todos los "Espiritu Santo" por "Espirito Santo". Sería genial si @ZurMaD lo corrige para los reportes diarios de ahora en adelante.
