### ISSUE TITLE
[Automation] Paraguay

### ISSUE THREAD

**Issue by ivanMSC** [DataScienceResearchPeru/covid-19_latinoamerica#55]
En este artículo de Wikipedia está el numero de casos por fecha y por departamento. 
https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_Paraguay

Si alguien quiere encargarse de automatizarlo

Los numeros de muertos o recuperados no están detallados por departamento.

Parte de #52

**Comment by pablodz** [comment]
Voy a buscar alguna API o proyecto ya que wikipedia cambia mucho su formato, si scrappeamos podría haber errores después

**Comment by pablodz** [comment]
#100 No se encontró fuentes para paraguay
