### ISSUE TITLE
[Automation] El Salvador

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#56]
We're going to[ scrap dashboards ](https://e.infogram.com/_/fx5xud0FhM7Z9NS6qpxs?src=embed)
I'm working on it.
Part of #52

**Comment by ivanMSC** [comment]
Ahí solo hay 6 de 78 casos detallados por departamento. Hay alguna otra fuente de los 72 restantes?

**Comment by pablodz** [comment]
Hola, necesito una mano con la automatización de el salvador, ya hice la parte de scrap archivo , lo deje en una variable que genera el siguiente dataframe en pandas, faltaría hacer que se integre a los reportes diarios!

Sin embargo, respondiendo a @ivanMSC tiene razón la data recopilada es incompleta.

**Comment by pablodz** [comment]
Parece que el título está mal, no muestra y está en constante cambio, se necesita otra página.

**Comment by pablodz** [comment]
Sin respuesta hasta la fecha, se deja sin soporte.


![image](https://user-images.githubusercontent.com/28235457/113090413-51a4ef00-91af-11eb-8063-442f41ec03d6.png)
