### ISSUE TITLE
[Automation] Honduras

### ISSUE THREAD

**Issue by ivanMSC** [DataScienceResearchPeru/covid-19_latinoamerica#57]
Parte de #52 
http://www.bvs.hn/COVID-19/

En ese sitio hay un dashdoard con el historial de casos confirmados por departamento.
También, hasta el fallecimiento número 15, se encuentra detallado con fecha y ciudad. Desde el fallecimiento 16 solo se detalla el departamento y no la fecha, aunque no debería ser difícil ponerse al día con alguna otra fuente.

Luego de estar al día con la data, correspondería scrappear la primera tabla de la pagina diariamente.

**Comment by ivanMSC** [comment]
bf98215 y 380eb0d 
Honduras al día. Quedaría solo hacer el bot, si alguien quiere encargarse. Sugeriría ir a esta fuente https://covid19honduras.org/ que es oficial del gobierno de Honduras. 

Del sitio de https://covid19honduras.org/ encontré [este Json](https://covid19honduras.org/dll/ODEPTO.php) con estructura que asumo es `id, Subdivision, ISO, Confirmados, Muertes, Recuperados`

**Comment by pablodz** [comment]
Entiendo que no se automatizó, esto es cierto? Para empezar a hacer el script para automatizar la data

**Comment by ivanMSC** [comment]
No. No está automatizado.

**Comment by pablodz** [comment]
Perfecto ahora empiezo con el script que estará en [esta carpeta](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/tree/master/utils/scripts). por cierto el json es suficiente para un scraping fácil 
![image](https://user-images.githubusercontent.com/28235457/78741062-fe8eb800-791d-11ea-8fe6-8bc63809df21.png)
pasado de json a tabla en http://json2table.com/


> No. No está automatizado.

**Comment by pablodz** [comment]
Está en semiautomático, genera un pandas, solo faltaría la parte de cambiar el archivo de la carpeta `daily_reports` de forma automática. El fin de semana @dfuribez quizás nos pueda echar una mano. Este es el [script ](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/utils/scripts/honduras_data.py)hasta ahora que tiene la data como se muestra en la imagen:
![image](https://user-images.githubusercontent.com/28235457/78746011-613a8080-792b-11ea-8c4e-fba05112e5ac.png)

Temporalmente estoy guardando la data en un csv en la [siguiente carpeta](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/tree/master/utils/scripts/honduras_temporal).

**Comment by dfuribez** [comment]
@ZurMaD @ivanMSC yo hoy por la noche o ya mañana me pongo con eso y de paso termino de retocar los otros scripts. si encuentran más APIS o páginas en donde se reporte la información de otros países por favor me avisan yo miro qué puedo hacer.

**Comment by ivanMSC** [comment]
Advertencia con los datos de Honduras: el Json del gobierno puede tener unos códigos ISO equivocados. Por ejemplo, Lempira es HN-LE y no HN-LM

@ZurMaD @dfuribez

**Comment by ivanMSC** [comment]
Está automatizado. Se actualiza todas las mañanas junto con los datos de Chile.

**Comment by pablodz** [comment]
Excelente, se puede cerrar el Issue entonces.
