### ISSUE TITLE
Using zeros for missing data.

### ISSUE THREAD

**Issue by carranco-sga** [DataScienceResearchPeru/covid-19_latinoamerica#59]
**Describe the bug**
Is there any agreed consensus in the way missing data should be handled? 

Commit a1a60bd2690069a4f52f31d52fda195ecac24693 by @dfuribez has changed some of the missing data I maintain to zeros; however, since March 23, Mexico's data reports don't include specifics on the number of recovered people, hence why I report it as ```missing```.

**Expected behavior**
Missing data should be dealt with consistently for any one country and the database as a whole so it is more useful.
The changes made in the commit are just a fraction of the required ones to have consistency in Mexico's data.
I will gladly make the changes to the data under my responsibility, to maintain reporting style if there is a consensus in the way missing data should be handled.

However, I think zero has a very precise definition: nothing. Treating data that is *not available* (*missing*, but not necessarily equal to zero) as zero, confuses me.
And well, putting personal biases aside, it's much easier to "complete" the data replacing ```missing``` with zeros than vice-versa. A simple line of regex magic does the trick in these cases.

**Files with the bug**
Refer to a1a60bd2690069a4f52f31d52fda195ecac24693.

Pinging contributors: @ZurMaD @rafnixg @RcrdPhysics @pablora19 @martingra @mamanipatricia @leytzher @josetup123 @ivanMSC @diegocl02 @dfuribez @ariasbordahugo @pablorea @rendergraf @Caospierre

**Comment by ivanMSC** [comment]
I vote for blanks.

**Comment by RcrdPhysics** [comment]
I vote for blanks.

**Comment by dfuribez** [comment]
Yeah, I totally agree we need a way to differentiate between nothing and not reported data. I mentioned that problem on Slack a few days ago and I was told just to change all "missing" values for zeros.

And I'm sorry if I'm messing with your work.

**Comment by carranco-sga** [comment]
No harm done, @dfuribez. I hope this issue allows us to have a more useful database.

**Comment by pablodz** [comment]
Scripts need changes to allow blank spaces and we need to review all dataset to don't clear blank spaces.

**Comment by carranco-sga** [comment]
All missing strings in Mexico's data should've been changed to empty strings by 8cff18472d5683b7abc3177d2940bc0e49a2412a.

**Comment by pablodz** [comment]
We're now using blanck spaces `` for missing data
