### ISSUE TITLE
Error de formato en Santo Domingo,Dominican Republic

### ISSUE THREAD

**Issue by ivanMSC** [DataScienceResearchPeru/covid-19_latinoamerica#6]
Hay un salto de línea:
```
"DO-01
",Santo Domingo,Dominican Republic,,,,,
```

**Comment by pablodz** [comment]
Notificado, arreglando el error, terminando subo el commit en el que fue arreglado.

**Comment by pablodz** [comment]
https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/f299300a406bc56ce88f0b6f88a51a30075447ef
