### ISSUE TITLE
VOLUNTER

### ISSUE THREAD

**Issue by marvinjqs** [DataScienceResearchPeru/covid-19_latinoamerica#60]
**Are you a newer contribuitor?**
Yes/No question just to know how to answer.

**How can you help us with tasks?**
Explain what do you want to contribute. We really appreciate your initiative.

**Comment by pablodz** [comment]
Hola, todavía estas interesado? Necesitamos voluntarios!

**Comment by rubenmarcus** [comment]
como puedo ayudar?

**Comment by pablodz** [comment]
Hola @rubenmarcus porfavor únete al Slack, necesitamos revolver muchos Issues. Igualmente @marvinjonathcn porfavor!
