### ISSUE TITLE
I want to contribute :)

### ISSUE THREAD

**Issue by scratchmex** [DataScienceResearchPeru/covid-19_latinoamerica#61]
**Are you a newer contribuitor?**
No

**How can you help us with tasks?**
Anything related to scripting, parsing, backend (API), automating or visualizing. I have a decent knowledge of Python for this things and open to contribute in anything else you need.

My initial idea is to create an awesome dashboard with [Dash](https://plotly.com/dash/).

PS: Awesome work you have done guys, really.

**Comment by ivanMSC** [comment]
Can you make a bot and have it cloud-hosted to run the scripts we have and have it commit once a day?

**Comment by scratchmex** [comment]
Sure!

**Comment by pablodz** [comment]
@scratchmex I'm adding you to the repository with `Maintainter` permission

**Comment by pablodz** [comment]
Also please join slack !
