### ISSUE TITLE
Reestructuración de la repo para automatización.

### ISSUE THREAD

**Issue by scratchmex** [DataScienceResearchPeru/covid-19_latinoamerica#63]
Como comentaba en el Slack:
- sería de mucha ayuda que los scripts de cada pais pertenezcan a la repo corrspondiente
- tener una carpeta llamada templates para poner todos los templates de csv's que se tienen en latam_covid_19_data
- en latam_covid_19_data unicamente tener los daily reports y per country reports
- el archivo timeseries propongo que se ponga en la raiz de la repo para accesibilidad y prioridad. Ahi estará toda la información condensada.
- mover información no correspondiente a casos del covid a una nueva repo y añadir un link a ella para alguna investigación que se quiera (como lo propuso #11 )

**Comment by pablodz** [comment]
> * sería de mucha ayuda que los scripts de cada pais pertenezcan a la repo corrspondiente

No entiendo esto, podrías detallarlo porfavor.

> * tener una carpeta llamada templates para poner todos los templates de csv's que se tienen en latam_covid_19_data

No entiendo el propósito de la tabla templates, podrías detallarmelo porfavor.

> * en latam_covid_19_data unicamente tener los daily reports y per country reports

Elegi esa estructura porque seguíamos el modelo de la data del CSSEGIS en un principio. 

> * el archivo timeseries propongo que se ponga en la raiz de la repo para accesibilidad y prioridad. Ahi estará toda la información condensada.

Tenemos un API no creo que sea necesario además que será un archivo extenso por lo que no tendrá visibilidad. 

> * mover información no correspondiente a casos del covid a una nueva repo y añadir un link a ella para alguna investigación que se quiera (como lo propuso #11 )

Esto sí es necesario, moveré esa data a otro repo, será eliminada en los siguientes días.

**Comment by scratchmex** [comment]
> No entiendo esto, podrías detallarlo porfavor.

No habia entendido bien como funcionaban los scripts, ya tengo claro eso una disculpa.

> No entiendo el propósito de la tabla templates, podrías detallarmelo porfavor.

Muchos archivos de los que estan son templates, es decir, están vacios y creo que conglomeran la información. Sería mejor que pusieramos los templates para que asi se puedan dar una mejor idea de la estructura. En el PR #64 que hice se ve mas o menos mi intención.

> Elegi esa estructura porque seguíamos el modelo de la data del CSSEGIS en un principio.

Si de hecho esta genial, lo comentaba porque muchos archivos estaban repetidos o vacíos. Puedes checar mi intención en el PR #64 

> Tenemos un API no creo que sea necesario además que será un archivo extenso por lo que no tendrá visibilidad.

Creo que tienes razón en ese aspecto, se repetiria información. Lo decia para una mejor accesibilidad para personas que quieren descargar el dataset sin tener que hacer un merge de todos los archivos en daily_reports. Habrá que ver con el timpo pero por el momento es cierto que no es es necesario. La api de hecho no deberia hacer ese merge por la alta necesidad de computo y memoria, alentaria las conexiones. Hay que discutir un poquito mas sobre eso, pero mi punto era por la api y la accesibilidad.

> Esto sí es necesario, moveré esa data a otro repo, será eliminada en los siguientes días.

Perfecto :)

**Comment by ZurMaD** [comment]
@all-contributors please add @scratchmex for data

**Comment by pablodz** [comment]
@all-contributors please add @scratchmex for doc
