### ISSUE TITLE
Hola, me gustaría contribuir con información sobre algún país faltante.

### ISSUE THREAD

**Issue by Fiamma2404** [DataScienceResearchPeru/covid-19_latinoamerica#67]
Hola, quisiera saber si aun se puede contribuir con la recopilación de información sobre países faltantes?

Saludos.

**Comment by scratchmex** [comment]
Tu PR siempre es bienvenido para paises faltantes

**Comment by pablodz** [comment]
Hola @Fiamma2404 hay una tabla en el `README.md` principal que muestra a los países de los cuales no se tiene data como `WITHOUT MAINTENANCE`
