### ISSUE TITLE
Formato de Issues

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#7]
Se agregó formatos para los formatos de creación de Issues:
[.github/ISSUE_TEMPLATE](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/tree/master/.github/ISSUE_TEMPLATE)

Se pueden agregar más como los siguientes:
[bug_report.md](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
[feature_request.md](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/.github/ISSUE_TEMPLATE/feature_request.md)

Se requiere dar un formato adecuado y preveer la llegada de más usuarios. Para poder dar un correcto soporte al repositorio.

**Comment by ZurMaD** [comment]
@all-contributors add @ZurMaD for admin
