### ISSUE TITLE
[Automation] México

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#72]
Estimado @carranco-sga , estamos automatizando todo el proceso de extraer data, al subir la información lo estás haciendo de forma manual o ya que tu país liberó los datos los podríamos extraer directamente con scripts. Quisiera saber cómo es el flujo de datos.

Gracias.

**Comment by carranco-sga** [comment]
Hola.

Actualmente lo que realizo es extraer la información de los datos abiertos en una [tabla resumen](https://github.com/carranco-sga/Mexico-COVID-19/blob/master/Mexico_COVID19_CTD.csv) usando [scripts](https://github.com/carranco-sga/Mexico-COVID-19/blob/master/Migrate.jl) que tengo disponibles en mi repositorio principal. De alli, ejecuto [un script](https://github.com/carranco-sga/COVID_databases_scripts/blob/master/latam.jl) que actualiza los datos de este repositorio.usando los datos de esa tabla.

Este flujo de trabajo es en parte heredado de la forma en la que se publicaban los datos originalmente.
Puedo automatizar el proceso para este repositorio, aunque necesito ver la manera de juntar los scripts correspondientes. 
Debería de tener algo funcional en uno o dos días.

Saludos,
Gabriel.

**Comment by pablodz** [comment]
Me parece perfecto la forma, se considera automatizado completamente ya que es correr un script.
Gracias por aclararlo, ya estamos logrando automatizar varios países.
