### ISSUE TITLE
Ausencia de Santiago del Estero - Argentina

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#8]
Santiago del Estero ausente en normado ISO 3166-2

**Comment by pablodz** [comment]
Se actualizará Santiago del Estero en todos archivos anteriores al 2020-03-23

**Comment by martingra** [comment]
Perdón, solo faltaba en los últimos archivos. Ya estarían todos los archivos completos.
