### ISSUE TITLE
Data faltante en Espirito Santo, BR

### ISSUE THREAD

**Issue by ivanMSC** [DataScienceResearchPeru/covid-19_latinoamerica#80]
**Describe the data error**
Espirito Santo, Brasil, no tiene data desde ell 25 de marzo

**Where's the error?**
Please attach links to files. Or if there's a lot of them attach the directory.
![image](https://user-images.githubusercontent.com/35350256/82746205-2fef0600-9d5b-11ea-82b0-642db766dfb8.png)

**Describe the solution you'd like**
Probablemente el código esta fallando al comparar `Espirito` con `Espiritu`. Recuerdo que esto había pasado antes. Tal vez sea lo mismo esta vez. Si es posible, usar códigos ISO para comparar.

**Additional context**

**Comment by ivanMSC** [comment]
#54

**Comment by pablodz** [comment]
Modificaré el script, estuvo diseñado principalmente para comparar con nombre de subdivision

**Comment by pablodz** [comment]
![image](https://user-images.githubusercontent.com/28235457/82760170-72463080-9db7-11ea-8bbb-61597b99f3bf.png)
