### ISSUE TITLE
time_series desde Junio 6

### ISSUE THREAD

**Issue by jzamalloa1** [DataScienceResearchPeru/covid-19_latinoamerica#83]
No veo nueva data en time_series desde Junio 6, este folder seguira siengo actualizado o deberiamos de obtener la data de los daily_cases?

Gracias

**Comment by pablodz** [comment]
Hola @jzamalloa1 tenemos un script automático que convierte la data a `time_series`, ahora revisamos que puede estar pasando ya que si se ejecuta a diario. 
[Script Timeseries](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/tree/master/utils/scripts/data_time_series)

**Comment by pablodz** [comment]
He revisado el código, por alguna razón no se ejecutaba, cerraré el issue cuando lo resuelva.

**Comment by jzamalloa1** [comment]
Gracias! Por si acaso la data the Brasil tampoco se veia, solo la de Chile.

**Comment by pablodz** [comment]
Creo que ya se arregló, sin embargo, los datos demoran y se tiene un offset mínimo de un día.
