### ISSUE TITLE
Peru 0 Data

### ISSUE THREAD

**Issue by jzamalloa1** [DataScienceResearchPeru/covid-19_latinoamerica#84]
La data de Peru en el time_series esta llena de 0s desde el 14 de Junio, la podrian revisar por favor?

**Comment by pablodz** [comment]
Los datos los obtenemos gracias a jmcastagnetto ya que hace la labor de pasar de forma manual los datos. Parece que no ha subido información desde hace 4 días, vamos a contactarlo y ver qué pasó para poder o esperar o cambiar a otro usuario que nos apoye con esa labor.

https://github.com/jmcastagnetto/covid-19-peru-data/tree/master/datos

**Comment by pablodz** [comment]
Ya encontramos el error, sucede que cambiaron el `branch` en el cuál almacenaban los datos. En breve realizaré el commit que lo arregla.

**Comment by pablodz** [comment]
Fue arreglado en este commit https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/b54376048d42fd8453fa36cbfff590d84f3da74c
y el cambio en el script automatizado fue este https://github.com/DataScienceResearchPeru/utils/scripts/data_collection/data/peru_data.py

Considero que se ha solucionado el problema, cierro issue #84

**Comment by jzamalloa1** [comment]
Perfecto, muchas gracias.
