### ISSUE TITLE
Problemas de codificación?

### ISSUE THREAD

**Issue by ivanMSC** [DataScienceResearchPeru/covid-19_latinoamerica#85]
**Describe the bug**
Al parecer alguno de los commits de datos automatizados escriben texto con codificación extraña.

**Expected behavior**

**Files with the bug**
latam_covid_19_data/daily_reports/2020-06-21.csv
![image](https://user-images.githubusercontent.com/35350256/85246523-dbea4680-b418-11ea-8b6e-4a964941ad2b.png)

latam_covid_19_data/daily_reports/2020-06-20.csv
![image](https://user-images.githubusercontent.com/35350256/85246610-1b189780-b419-11ea-97ce-1b36e6f84a34.png)

etc...

**Additional context**
Por lo que he visto, el bug esta desde 2020-06-17.csv en adelante.
El problema no es solo Cuba.

**Comment by pablodz** [comment]
Ahora lo reviso, hace unos días automatice todo a un one single clic.exe. Ya tengo idea de masomenos que puede ser

**Comment by pablodz** [comment]
Arreglado manualmente, veré si se vuelve a generar estos días.
Tiempo de espera por errores: 3 días. hasta entonces el Issue abierto
c5fae2d40ba4687d54d48bd1545e7d8223253b50
