### ISSUE TITLE
Create a workflow that get information each time that sources changes

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#87]
Automation

**Comment by scratchmex** [comment]
Lo que comenté en la issue #52. Sólo déjame entender como funcionan los scripts y trabajo en esto.
El workflow no seria automático sino programado.

**Comment by scratchmex** [comment]
Si me apoyas con el workflow que sigues para actualizar me ayudaria mucho @ZurMaD

**Comment by pablodz** [comment]
Es ejecutar este script de python https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/utils/scripts/update_data.py Lo estuve haciendo desde visual code que crea un entorno como si el repositorio fuera el root_path
