### ISSUE TITLE
Argentina hasta Junio 16

### ISSUE THREAD

**Issue by jzamalloa1** [DataScienceResearchPeru/covid-19_latinoamerica#88]
Hola,

Podrian revisar la data de las provincias de Argentina, solo va hasta Junio 16.

Gracias

**Comment by pablodz** [comment]
Se debía a que Datos Abiertos Argentina dejó de reportar, pero vamos a verificar nuevamente.

**Comment by pablodz** [comment]
![image](https://user-images.githubusercontent.com/28235457/87101845-c6955a80-c215-11ea-8672-8bce51a01e81.png)
Como vemos en la imagen, no actualizan desde junio su base de datos :/

**Comment by pablodz** [comment]
Actualización 2020-08-18, siguen sin actualizar los datos a la fecha actual

![image](https://user-images.githubusercontent.com/28235457/90551379-d5e1bf00-e156-11ea-8df9-2f22a197d6f9.png)

**Comment by pablodz** [comment]
Actualización 2020-12-11 Argentina sigue sin actualizar sus datos

**Comment by pablodz** [comment]
Actualización 2021-05-16, Argentina actualiza sus datos semanalmente  https://datos.gob.ar/dataset/salud_68d8469d-f38c-4486-a673-b7ca0e20c36a/archivo/salud_fd657d02-a33a-498b-a91b-2ef1a68b8d16


Se tratará de implementar el actualizador automático

**Comment by pablodz** [comment]
Actualización terminada, script automático funcionando.
