### ISSUE TITLE
Peru - Lima, desde Julio 11

### ISSUE THREAD

**Issue by jzamalloa1** [DataScienceResearchPeru/covid-19_latinoamerica#89]
Hola,

Al parecer no hay datos en Lima desde Julio 11, lo pueden revisar por favor?

Gracias,
Jose

**Comment by pablodz** [comment]
Ahora vemos los cambios

**Comment by pablodz** [comment]
Encontramos el error, trataremos de repararlo lo antes posible.
Archivos comprometidos:
- `2020-07-05.csv` hasta `2020-07-20.csv`

![image](https://user-images.githubusercontent.com/28235457/87989719-29091900-caa8-11ea-963b-07690a0a0934.png)

**Comment by pablodz** [comment]
Nuestra fuente de datos cambió los nombres de reconocimiento, procederemos a sumar las cantidades de Lima metropolitana y Lima Region ya que son complementos de un Departamento llamado `Lima`

**Comment by ZurMaD** [comment]
Problema resuelto.
![image](https://user-images.githubusercontent.com/28235457/87991632-30322600-caac-11ea-963e-80b9a911cc1e.png)

Commit: https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/b463fcc540c481387ba1f7c9bcab4a0b0240dc76

**Comment by pablodz** [comment]
![image](https://user-images.githubusercontent.com/28235457/87993149-6a50f700-caaf-11ea-827b-126133cfce51.png)
Fixed https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/commit/b463fcc540c481387ba1f7c9bcab4a0b0240dc76

**Comment by jzamalloa1** [comment]
Listo, muchas gracias!
