### ISSUE TITLE
Agregar subdivisión administrativa nula para Chile

### ISSUE THREAD

**Issue by ivanMSC** [DataScienceResearchPeru/covid-19_latinoamerica#9]
**Is your feature request related to a problem? Please describe.**
El Ministerio de Salud de Chile es tan inoperante, que solo entrega cifras de los casos recuperados a nivel nacional y no desagregado por Región (subdivisión administrativa). Tengo los datos día a día del número de recuperados, pero no tengo donde escribirlos en los reportes diarios.

**Describe the solution you'd like**
Agregar una subdivisión administrativa `NULL` para Chile. O algo como `CL-NULL`, `Sin informacion`

**Describe alternatives you've considered**
Alternativamente pensé en agregarlos con la Región de Santiago (Capital). Pero esto sería deshonesto.

**Additional context**
Gobierno de mierda.

**Comment by pablodz** [comment]
Una solución podría ser mantener la data de recuperados de los días anteriores y dejar este [Issue ](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/issues/9) abierto hasta que el Gob. de Chile brinde esa información, si lo hace.

**Comment by pablodz** [comment]
Hola, tengo entendido que el gobierno dejó de reportar a partir del 27 de marzo

**Comment by ivanMSC** [comment]
No. Siguen reportando el número a nivel nacional.

**Comment by pablodz** [comment]
Hola, ¿alguna novedad?

**Comment by ivanMSC** [comment]
Nada nuevo

**Comment by ivanMSC** [comment]
Desde ahora en Chile se están informando los recuperados por Región. 
Cierro issue...
