### ISSUE TITLE
Error detectado en mapa virtual

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#90]
He revisado el mapa virtual y no está mostrando datos hasta la fecha de hoy. Quizás sean los datos o sea el DataStudio.
En todo caso revisemos los dos

**Comment by pablodz** [comment]
![image](https://user-images.githubusercontent.com/28235457/90550941-44724d00-e156-11ea-895f-912a8ed0d92f.png)

Se arregló solo wtf

**Comment by ivanMSC** [comment]
Cosas de datastudio jaja 🤷🏻‍♂️

**Comment by pablodz** [comment]
Misterios del universo, la fe de los bits jaja
