### ISSUE TITLE
Data de Panama

### ISSUE THREAD

**Issue by jzamalloa1** [DataScienceResearchPeru/covid-19_latinoamerica#91]
Hola, tienen planes de seguir obteniendo datos de Panama? No veo los datos mas recientes en la tabla.

Gracias.

**Comment by pablodz** [comment]
Su gobierno no está mostrando los datos al público
![image](https://user-images.githubusercontent.com/28235457/92196380-c8a22100-ee34-11ea-8020-8b9e41672b57.png)

**Comment by pablodz** [comment]
Al día de hoy, 2021-06-21 no se ha encontrado fuentes para Panamá, se quita soporte
