### ISSUE TITLE
FinMango - Data Publishing License

### ISSUE THREAD

**Issue by becloo** [DataScienceResearchPeru/covid-19_latinoamerica#92]
Hello,

I am a volunteer for FinMango, a non-profit organisation. We are working on a project with the mission of building a detailed COVID data repository which is inclusive to all local communities (https://finmango.org/covid) and various countries across the globe. We came across your source and found it to be a brilliant dataset for our Latin America data! Unfortunately, the licence under which you publish your data outputs is very restricting. The data in our project is licensed as CC BY, but if we wanted to use some of your project’s data, we would have to change our license to CC BY SA to comply with the ShareAlike clause. Would you consider switching to the less restrictive version of the license, without the ShareAlike clause? Another project with great data which recently switched from CC BY SA to CC BY is https://covidtracking.com. 

I look forward to hearing from you! Thank you.

Best, 

Rebeca Lozano
Volunteer, FinMango

**Comment by pablodz** [comment]
Hello @rebecalozano , glad to see others non-profit organizations working around the globe, we release a License for non-profit orgs (CC BY 4.0) that supersede the general (CC-BY-SA 4.0) one that you mention before. You can find the general one [here](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/LICENSE.md) and for non-profit orgs [here](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/LICENSE_NP_ORGS.md). Thanks for contact! If you want to suggest, recommend or say something please feel free.

Now, for NP-ORGS:
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://licensebuttons.net/l/by/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Latin America Covid-19 Data Repository</span> by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Data Science Research Peru</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International (CC BY 4.0)</a>.

**Comment by becloo** [comment]
Hi @ZurMaD ,
Thank you for the quick action on this! Since the data is now licensed as CC BY for our use, I presume it would be OK to republish it as part of our datasets with the same CC BY license, correct?

We are working with multiple partners which unfortunately can't make use of the data if it has the ShareAlike clause. If there is any additional information you can provide, I would greatly appreciate it.

Thanks in advance!

**Comment by pablodz** [comment]
> Thank you for the quick action on this! Since the data is now licensed as CC BY for our use, I presume it would be OK to republish it as part of our datasets with the same CC BY license, correct?

Yes, it's correct. The NP ORG now can re-distribute the data in any way, even with commercial purposes. 

> We are working with multiple partners which unfortunately can't make use of the data if it has the ShareAlike clause. If there is any additional information you can provide, I would greatly appreciate it.

In our case, we just wanted to be contacted. We will give them a CC BY 4.0 license. We put the CC-BY-SA 4.0 because we want to know where's being used the data and how. Just keep contacting, people who work around covid are usually want to stop the spread covid-19.

**Comment by MangoScott** [comment]
Hi @ZurMaD I'm working with @rebecalozano on the FinMango project linked above. 

It looks like the license you added to the repo is not CC By. It still contains the non-commercial clause, and that might be an issue for some of our collaborators (which are not deriving profit from this, but are part of the for-profit entities). 

For us to be able to re-publish the data as CC By, you should use the CC BY license verbatim: https://creativecommons.org/licenses/by/4.0/legalcode.txt 

Can you update the license file to that?

**Comment by pablodz** [comment]
Fixed, please confirm

**Comment by MangoScott** [comment]
Hi @ZurMaD, thanks for the speeding response. The fact that it's a dual-license makes our collaborators not want to touch your data anymore... It'll be best if you drop the non-profit license and simply switch the "CC BY SA" to "CC BY" license: https://creativecommons.org/licenses/by/4.0/

**Comment by MangoScott** [comment]
@ZurMaD ^^^

**Comment by pablodz** [comment]
Hi @MangoScott , is not possible to change our license in that way. We choose Multi-licensing because, as I said, we need to know how the data is being used.  With the license granted to FinMango you can fork the repo and re-distribute with other licenses, like CC-BY, or use the repository directly. The image below illustrates my words.

![Diagrama en blanco](https://user-images.githubusercontent.com/28235457/95373228-52189900-08a2-11eb-9143-a42a6aabb2dc.png)
