### ISSUE TITLE
Drastic size gain

### ISSUE THREAD

**Issue by pablodz** [DataScienceResearchPeru/covid-19_latinoamerica#94]
Now, the repo's size is around 1 GB.
Can be easily under 100 MB.
Big files are related to getting a back-up from source files.
What we should do?
- Stop back-uping source files.
- Store back-up in other web?
??

![image](https://user-images.githubusercontent.com/28235457/97059687-b8fea900-1556-11eb-9b20-64beaaaebea2.png)

**Comment by carranco-sga** [comment]
One alternative would be uploading those files to a secondary location using git-lfs.

**Comment by pablodz** [comment]
Already fixed for the whole branch, deleted history track of per_patient/*
