### ISSUE TITLE
Automatic updates not working since 2020-12-09.

### ISSUE THREAD

**Issue by carranco-sga** [DataScienceResearchPeru/covid-19_latinoamerica#95]
**Describe the bug**
The automated Google Apps script (by @ivanMSC) hasn't run since 2020-12-08.

**Expected behavior**
The script should continue running, and providing the necessary updates to the repo.

**Comment by pablodz** [comment]
Also datastudio is showing error https://datastudio.google.com/u/2/reporting/9b824956-4055-46da-8c40-0d46ded5ffba/page/QkcKB 

![image](https://user-images.githubusercontent.com/28235457/101973506-a9bae400-3c06-11eb-8b06-b1e4211fd32a.png)

**Comment by ivanMSC** [comment]
El servicio UrlFetchApp de Google esta funcionando de forma intermitente para archivos csv. Por lo tanto no puedo llamar archivos csv de forma confiable. La gente de Google esta trabajando en ello. 

https://support.google.com/docs/thread/87544571?hl=en

No tengo como hacer commits automáticos en este repositorio, ya que necesito leer los csv para editarlos, y no es posible sin el servicio UrlFetchApp.

**Comment by pablodz** [comment]
[Actualización 2020-12-15] Sigue sin ser solucionado por parte de Google

**Comment by pablodz** [comment]
[Actualización 2020-12-15] Parece que volvió a la normalidad, supongo que como de rutina mañana se ejecutará el script de Chile

![image](https://user-images.githubusercontent.com/28235457/102291940-310f9c80-3f12-11eb-9920-9f24829505de.png)

**Comment by pablodz** [comment]
[Actualización 2020-12-15] Scripts funcionando, para los días que no se tomaron data pueden optar por omitirlo o actualizarlo, decidan, ya que creo con simple interpolación se pueden estimar los datos faltantes. Saludos, gracias por su tiempo.

**Comment by ivanMSC** [comment]
Tengo guardados los datos que faltan. Los cargo en cuanto pueda.
