### ISSUE TITLE
Github action for updating the data failed for 2021-04-14.

### ISSUE THREAD

**Issue by carranco-sga** [DataScienceResearchPeru/covid-19_latinoamerica#96]
**Describe the data error**
The Github action used to update the data daily failed on 2021-04-14, making the file for this day unavailable.

**Where's the error?**
The update action in the repo.

**Comment by pablodz** [comment]
Yes, however once it's created will run without problems. It's scheduled to run daily

**Comment by carranco-sga** [comment]
It actually ran for 2020-04-14, but it failed during execution: https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/actions/runs/749654212

**Comment by pablodz** [comment]
Fixed :)
